specVersion: 0.2.0
name: subQLPlayground
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527' # Genesis hash of Moonriver
  endpoint: wss://moonbeam-alpha.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/moonbase-alpha-dictionary
dataSources:
  - kind: substrate/Moonbeam
    startBlock: 752073
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        # Must be a key of assets
        abi: zoombiesMarket
        ## The contract that emitted the event
        address: '0x6bd193ee6d2104f14f94e2ca6efefae561a4334b'
    assets:
      zoombiesMarket:
        file: './erc20.abi.json'
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleMoonbeamEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Transfer(address indexed from,address indexed to,uint256 value)
              - null
              - null
              - null

