specVersion: 0.2.0
name: subQLPlayground
version: 1.0.0
description: ""
repository: ""
schema:
  file: ./schema.graphql
network:
  genesisHash: "0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b" # Genesis hash of Moonriver
  endpoint: wss://moonriver.api.onfinality.io/public-ws
  dictionary: "https://api.subquery.network/sq/subquery/moonriver-dictionary"
dataSources:
  - kind: substrate/Moonbeam
    startBlock: 752073
    processor:
      file: "./node_modules/@subql/contract-processors/dist/moonbeam.js"
      options:
        # Must be a key of assets
        abi: zoomToken
        ## The contract that emitted the event
        address: "0x8e21404bAd3A1d2327cc6D2B2118f47911a1f316"
    assets:
      zoomToken:
        file: "./zoomToken.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleMoonbeamEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Transfer(address indexed from,address indexed to,uint256 value)
              - null
              - null
              - null
