specVersion: "0.2.0"

name: "subQLPlayground"
version: "1.0.0"
description: "A basic Moonriver EVM example project with an event and call handler. Read more about this at https://doc.subquery.network/create/moonbeam/"
repository: "git@github.com:mchigit/subqueryPlayground.git"

schema:
  file: "./schema.graphql"

network:
  genesisHash: "0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b" # Genesis hash of Moonriver
  endpoint: wss://moonriver.api.onfinality.io/public-ws
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  dictionary: "https://api.subquery.network/sq/subquery/moonriver-dictionary"

dataSources:
  - kind: substrate/Moonbeam
    startBlock: 752073
    processor:
      file: "./node_modules/@subql/contract-processors/dist/moonbeam.js"
      options:
        # Must be a key of assets
        abi: zoomToken
        ## The contract that emitted the event
        address: "0x8e21404bAd3A1d2327cc6D2B2118f47911a1f316"
    assets:
      zoomToken:
        file: "./zoomToken.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleMoonbeamEvent
          kind: substrate/MoonbeamEvent
          filter:
            ## Topics that follow Ethereum JSON-RPC log filters
            ## https://docs.ethers.io/v5/concepts/events/
            ## With a couple of added benefits:
            ##  - Values don't need to be 0 padded
            ##  - Event fragments can be provided and automatically converted to their id
            topics:
              ## Example valid values:
              # - '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
              # - Transfer(address,address,u256)
              # - Transfer(address from,address to,uint256 value)

              ## Example of OR filter, will capture Transfer or Approval events
              # - - 'Transfer(address indexed from,address indexed to,uint256 value)'
              #   - 'Approval(address indexed owner, address indexed spender, uint256 value)'

              - Transfer(address indexed from,address indexed to,uint256 value)
              ## topics[1] to topics[3] are the indexed values
              - null
              - null
              - null
